### ISSUE TITLE
New 1.1.3 security group creation fails for deployments

### ISSUE THREAD

**Issue by dpiddockcmp** [kubernetes-sigs/aws-alb-ingress-controller#1028]
Hi,

I was trying out the new security group creation process introduced in 1.1.3 and it works fine with single pod workloads. However the ENI security group detection fails when the backing workload is a deployment, even if there's only one replica.

Key error in the log:
`
controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: failed to describe all securityGroups, expect: map[], got: 7"  "controller"="alb-ingress-controller" "request"={"Namespace":"test","Name":"echo"}
`

The error is then repeated until the Ingress is either removed or a security group annotation added.

Full, but slightly sanitised, logs and the YAML used in [this gist](https://gist.github.com/dpiddockcmp/27121f427fb36c44c53a4ccf820406ac)

**Comment by M00nF1sh** [comment]
Hi, i can confirm this error happens when under IP target-type and there is no replica in the deployment. 
caused by this line:https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/alb/sg/instance_attachment_v2.go#L104
Is this the case for you or are u using kubenet instead of amazon-vpc-cni-k8s.

**Comment by M00nF1sh** [comment]
created an PR to fix, not sure whether your case is caused by this.

**Comment by dpiddockcmp** [comment]
Hi @M00nF1sh, I can confirm that the new v1.1.3 has fixed this issue for me.

Thank you 😄

**Comment by kamalperumal** [comment]
Hello,

I'm encountering the same error as above

E0131 12:52:37.524644       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/ceng-eks-dev on eni eni-0f65b7aded0bdc0a1, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"sun-web-dev","Name":"2048-ingress"}
E0131 12:55:23.580341       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile securityGroup associations due to failed to reconcile instance securityGroup attachment: expect one securityGroup tagged with kubernetes.io/cluster/ceng-eks-dev on eni eni-0f85b01ce93f35590, got 2"  "controller"="alb-ingress-controller" "request"={"Namespace":"sun-web-dev","Name":"2048-ingress"}
