### ISSUE TITLE
Ingress ConfigMap

### ISSUE THREAD

**Issue by Awk34** [kubernetes-sigs/aws-alb-ingress-controller#109]
Is there a way to set metadata for an ingress resource (ex subnets, security group, etc) via a ConfigMap?

**Comment by justinclayton** [comment]
It looks like the answer is not currently. According to [this snippet](https://github.com/coreos/alb-ingress-controller/blob/master/controller/controller.go#L121-L124), it appears that `SetConfig` from the parent class has been implemented, but it just logs the data instead of storing it. Seems like a good idea though. +1!

**Comment by joshrosso** [comment]
@Awk34 @justaugustus I agree, this would be a good and a way for us to stay aligned with the existing ingress controller(s).

Might not tackle this until host-based routing is fleshed out. Feel free to throw a PR in if you find time to take a stab at it.

Thanks!

**Comment by Awk34** [comment]
@joshrosso We'll see, I'm still trying to learn Go ;D
