### ISSUE TITLE
AWS Config non-compliant

### ISSUE THREAD

**Issue by lee5i3** [kubernetes-sigs/aws-alb-ingress-controller#1147]
alb-ingress-controller version: docker.io/amazon/aws-alb-ingress-controller:v1.1.2

I have my ingress with the following annotations:
```
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

We are using AWS Config to ensure we are compliant, however the AWS managed rule **alb-http-to-https-redirection-check** is failing for all our ALB

After talking to AWS support, it is non-compliant because the requirement for that rule is EVERY rule in HTTP has to be redirecting to HTTPS, and with our current setup, only first rule is doing that.

Is there a workaround for this?

**Comment by M00nF1sh** [comment]
Hi, there is no workaround for this due to our original design for [http->https redirection support](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/). 
TBH, its bit hack from user interface and implementation 🤦‍♀️

Going forward, i think a better idea is introduce a dedicated annotation for such task, e.g. `alb.ingress.kubernetes.io/https-redirection:true`  redirection.

**Comment by M00nF1sh** [comment]
pending release contain https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1162
