### ISSUE TITLE
etag value is missing 

### ISSUE THREAD

**Issue by daparthi001** [kubernetes-sigs/aws-alb-ingress-controller#1151]
I am trying to hit the url based out of the alb ingress controller ,but i having 404 because its missing the etag value.Any help ?
**Through the url from the alb** 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: awselb/2.0
Server: awselb/2.0
< Date: Mon, 03 Feb 2020 18:18:02 GMT
Date: Mon, 03 Feb 2020 18:18:02 GMT
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Content-Length: 0
Content-Length: 0
< Connection: keep-alive
Connection: keep-alive
When pod is connected through the cluster ip on the port **directly**

< HTTP/1.1 200
HTTP/1.1 200
< Accept-Ranges: bytes
Accept-Ranges: bytes
< ETag: W/"3966-1580329253000"
ETag: W/"3966-1580329253000"
< Last-Modified: Wed, 29 Jan 2020 20:20:53 GMT
Last-Modified: Wed, 29 Jan 2020 20:20:53 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 3966
Content-Length: 3966
< Date: Mon, 03 Feb 2020 18:17:56 GMT
Date: Mon, 03 Feb 2020 18:17:56 GMT

**Comment by M00nF1sh** [comment]
@daparthi001 
are u access the ALB using the correct host name and port? e.g. If you used host:example.com and path: /home, you need to access it via "example.com/home" instead of "alb-dns/home". You can remove the hostName condition from Ingress if you'd like to access using any hostname like alb-dns.

As for the ETAG issue, i don't have experience on this behavior, you'll need to open a support case to ALB Service for answer.
