### ISSUE TITLE
Target group creation not behaving as expected

### ISSUE THREAD

**Issue by max-l-weaver** [kubernetes-sigs/aws-alb-ingress-controller#1152]
Disclaimer: I'm fairly new to EKS, ingress-controllers and AWS in general.

I've deployed an alb ingress with subnet autodiscovery. I have also tagged up the instances in my public subnet with the appropriate tags:

```
      "kubernetes.io/cluster/<cluster-name>" = "shared"
      "kubernetes.io/role/elb" = "true"
```
When the ingress is deployed it creates an alb and associated tg but the target group has all my instances in, including those in my private subnets that I don;t want exposed to the alb. I just want those with the above tags exposed.

I have also tried explicitly specifying my public subnets using the `alb.ingress.kubernetes.io/subnets` annotation but I still see the same behaviour.

Perhaps I am missing something here? Any guidance would be greatly received.

**Comment by M00nF1sh** [comment]
Hi, 
1. the tags only need to be applied to subnet instead of instances, and it's doesn't affect which backends are been used. It just tell ALB which subnet they should use for their LoadBalancing Nodes.
2. There are two option for this currently:
   1. continue use the default "instance" traffic mode, and for instances that don't want to be included as backends, modify the corresponding Node object in k8s to have an label `alpha.service-controller.kubernetes.io/exclude-balancer: true`.
   2. switch to use 'ip' traffic mode by add 'alb.ingress.kubernetes.io/target-type: ip` to Ingress object(or Service object which only affects one service). This will register pods as backends directly. However, currently this mode cannot achieve zero downtime deployment if you have only a few backend pods.

**Comment by max-l-weaver** [comment]
hi @M00nF1sh 
Thanks for getting back to me. I can confirm that labelling my non-ingress nodes with the `exclude-balancer` tag has fixed the original issue.

Thanks again
