### ISSUE TITLE
Drop Invalid Header - Load balancer attribute

### ISSUE THREAD

**Issue by e-jjj** [kubernetes-sigs/aws-alb-ingress-controller#1175]
Hi,

Enabled the below annotation for the aws-alb-ingress controller

`alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=false`

Getting the error as shown below in the aws-alb-ingress controller logs,
```
E0227 00:14:44.209725       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile attributes of arn:aws:elasticloadbalancing:us-east-1:XXXXXX:loadbalancer/app/XXXXXXXXX/XXXXXXX due to failed parsing attributes; the load balancer attribute routing.http.drop_invalid_header_fields.enabled is not valid"  "controller"="alb-ingress-controller" "request"={"Namespace":"xxx-api","Name":"xxx-ingress"}
```

Can you please provide details as to how we can use this new annotation to set the load-balancer attribute?

Thanks

**Comment by SaranBalaji90** [comment]
What's your ALB Ingress controller image version? If you have built from master then this should work. Otherwise this will not work as the changes for this is not yet released.

This was added as part of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/commit/f83567dfde2694707ebf5b2d09e0c3ef3f2d4fec

But our latest tag 1.1.5 https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1130 was released few days before that commit.

**Comment by e-jjj** [comment]
@SaranBalaji90 I used the alb-ingress-controller chart to install/manage the controller. 

The chart version is aws-alb-ingress-controller-0.1.10 and APP version is v1.1.2 

Do you know how I could get the change from master ? Could I do it via the chart? 
https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller

**Comment by SaranBalaji90** [comment]
We haven't cut the release yet, so if you want to use this feature then you might have to check out the code, build docker image and push the image to your ecr repo. Will check if its possible through helm charts.

**Comment by e-jjj** [comment]
@SaranBalaji90 Thanks for your response. Were you able to check if its possible through helm charts?
Thanks
