### ISSUE TITLE
Auth annotations on service have no effect when using 'use-annotation'

### ISSUE THREAD

**Issue by patope** [kubernetes-sigs/aws-alb-ingress-controller#1193]
```
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
  annotations:
    alb.ingress.kubernetes.io/auth-type: none
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/actions.api-ann: |
      {
        "Type":"forward",
        "ForwardConfig":{
          "TargetGroups":[ 
            {
              "ServiceName":"api",
              "ServicePort":"8080"
            }
          ]
        }
      }
    alb.ingress.kubernetes.io/conditions.api-ann: |
      [
        { 
          "Field":"http-header",
          "HttpHeaderConfig":{
            "HttpHeaderName": "x-api-key", 
            "Values":["*"]
          }
        }
      ]
...
spec:
  rules:
      - path: /api/*
        backend:
          serviceName: api-ann
          servicePort: use-annotation
```
I want to disable oidc authentication on API endpoint when `x-api-key` is defined. I need oidc enabled on ingress because it's not possible to enable it separately on redirects and external targetgroup forwards.

Annotation on `alb.ingress.kubernetes.io/auth-type: none` on service has no effect, because of this check here https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/206154d817ae0c49cd1be475992768a57771469c/internal/ingress/auth/auth.go#L103

**Comment by M00nF1sh** [comment]
Hi,
By ALB's design, the authentication is based on path instead of backends.

We originally supported the feature to "configure annotations on service"  to workaround k8s IngressSpec's limitation that there is no way to configure path specific configuration, since there is always only one service per path.
However, with ALB's weighted targetGroups support, a single path can have multiple serviceBackend, but auth is still based on path. That's why i decided to not support auth on these services configured via annotation.

In summary, the annotation schema is like this:
1. configurations that applies to ALB Rules TargetGroup: we support configure them via annotation on either Service or Ingress.
2. configurations that applies to ALB Rules:
    * route conditions like `alb.ingress.kubernetes.io/conditions.api-ann`, where 'api-ann' is the referenced serviceName.
    * auth like `alb.ingress.kubernetes.io/auth-type`, it's supported on Ingress and Service when the service is not a "use-annotation" port.
       We could add a new annotation like `alb.ingress.kubernetes.io/auths.pi-ann.auth-type` to support path based auth, and deprecate the support for configure it on services.

BTW, for your case, since you are only use one service backend, you don't need to use the 'use-annotation', the conditions annotation can be applied to serviceNames that are not annotations based as well(i'll fix the docs about this). something like below:
```
annotations: 
    alb.ingress.kubernetes.io/conditions.api: |
      [
        { 
          "Field":"http-header",
          "HttpHeaderConfig":{
            "HttpHeaderName": "x-api-key", 
            "Values":["*"]
          }
        }
      ]
...
spec:
  rules:
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 8080
```

**Comment by patope** [comment]
@M00nF1sh Thanks! This resolves my issue.
