### ISSUE TITLE
Configmap for Automation

### ISSUE THREAD

**Issue by nightmouse** [kubernetes-sigs/aws-alb-ingress-controller#1340]
Setting the cluster name via `kubectl edit` makes automated deployments harder than it should be.  Would it be possible to use a configmap instead of commandline arguments for configuration?

For example: `kubectl create configmap albconfig --from-literal=cluster-name=foo`

Thanks!

**Comment by M00nF1sh** [comment]
Hi, i haven't tested it, but i think it should be possible now.
the clusterName can be specified via `CLUSTER_NAME` environment variable(instead of the --cluster-name commandline arg).
Then u can define that environment variable from configurations in configmap(https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-a-container-environment-variable-with-data-from-a-single-configmap)

**Comment by M00nF1sh** [comment]
closing this, feel free to reopen if needed :D
