### ISSUE TITLE
Allow default set of AWS Tags to be specified on the controller

### ISSUE THREAD

**Issue by matt-deboer** [kubernetes-sigs/aws-alb-ingress-controller#187]
[enhancement]
It would be convenient if I could specify a default set of Tags on the controller, such that all ALBs it creates would be given those tags (some of which might be overridden by an individual Ingress object's annotations).

**Comment by joshrosso** [comment]
Yeah, I like this a lot. Good way for companies to standardize. I'm going to mark this as `1.1` but I could see it making `1.0`.

**Comment by d-shi** [comment]
+1. We run multiple k8s clusters, and it would be nice to be able to specify tags to keep track of costs per cluster.

**Comment by hugohenley** [comment]
up

**Comment by michaelajr** [comment]
Was this implemented as an **_override_** to the annotation on the Ingress? Because that is the behavior we are seeing. If my Ingress has the tags annotation - then I would think they would take precedence over **_default_** tags that controller would use. So a union of the default tags and tags in the ingress annotation, where the tags specified on the ingress annotation take precedence if there is collision - is what I would expect. Otherwise you have _tag overrides_ - not _default_ tags.
