### ISSUE TITLE
Failed when used in aws region eu-west-2 (London)

### ISSUE THREAD

**Issue by msh111** [kubernetes-sigs/aws-alb-ingress-controller#563]
E0816 15:28:20.335901       1 albingresses.go:211] Failed to get associated Web ACL. Error: RequestError: send request failed
caused by: Post https://waf-regional.eu-west-2.amazonaws.com/: dial tcp: lookup waf-regional.eu-west-2.amazonaws.com on 10.214.0.3:53: no such host
I0816 15:28:20.335946       1 albingresses.go:101] Assembled 0 ingresses from existing AWS resources in 49.70894416s
F0816 15:28:20.335962       1 albingresses.go:103] Assembled 0 ingresses from 1 load balancers

Release:    1.0-beta.6
Build:      git-f740c293

**Comment by grockeek** [comment]
As far as I can see, It is the same problem encountered in issue #439 

This problem have also been seen in `eu-west-3`, where there's no WAF service (this error will be triggered anywhere this service is unavailable (availability [here](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/?nc1=h_ls))).

As @rifelpet suggested, a prerequisite of ALB creation would be a check through SDK function (documented [here](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#pkg-constants)); Resolving endpoint first, and taking action accordingly, would be interesting
I am working w/ m on a PR to develop this option.

@bigkraig : Regarding session information, I am digging around to easily retrieve region (configured through AWS profile/credentials). Do you have any suggestions in order to achieve it easily ?

**Comment by bigkraig** [comment]
@grockeek I've been using the AWS_REGION environment variable, AFAIK that is the only way to get it unless the app also accepts a parameter and overrides the client. aws-cli works the same way. Thanks for looking into this one!

I'm going to close this one since this is the same as #439.
