### ISSUE TITLE
Feature Request: AWS ALB Ingress Controller Helm Chart in Helm repository

### ISSUE THREAD

**Issue by Jeeppler** [kubernetes-sigs/aws-alb-ingress-controller#693]
To install AWS ALB Ingress Controller via Helm, the [APPR Helm Plugin](https://github.com/app-registry/appr-helm-plugin) has to be installed. This is a huge overhead for a single package.

It would be nice to be able to install AWS ALB Ingress Controller through the [Helm Charts](https://github.com/helm/charts) repository. If this is not possible, I would like to at least be able to install the AWS ALB Ingress Controller using the standard Helm tools. @d-nishi Maybe it is possible for AWS to host this Helm chart in their infrastructure. At the end this project can only be used on AWS infrastructure.

**Comment by M00nF1sh** [comment]
This make sense. I'll take some time next week to see how we can optimize this

**Comment by rifelpet** [comment]
#362 already discusses this and there is an open PR: https://github.com/helm/charts/pull/7236. It would be good to get that updated and merged.

**Comment by M00nF1sh** [comment]
me and kraig is still trying to find a guy to get our helm PR merged : (    (more than 300 pending PR in helm =.=)

In the meantime, will turn our github pages into a helm repo acceptable?
So users can do below to install without the registry plugin
`helm repo add alb-ingress https://kubernetes-sigs.github.io/aws-alb-ingress-controller`
`helm install alb-ingress/alb-ingress-controller`

ultimately, it should be inside helm repo, and we should have some helm repo memeber(or i'll try to become one), so that we can get our updates merged quickly.

**Comment by Jeeppler** [comment]
@M00nF1sh how far are you with turning the GitHub repo into a helm repo? 
So we can install it like this: 
```
helm repo add alb-ingress https://kubernetes-sigs.github.io/aws-alb-ingress-controller
helm install alb-ingress/alb-ingress-controller
```

**Comment by M00nF1sh** [comment]
I can finished it today 😄

**Comment by Jeeppler** [comment]
@M00nF1sh that would be awesome.

**Comment by M00nF1sh** [comment]
@Jeeppler PR #744  created :D

You can try out the github pages of my fork there 😄
