### ISSUE TITLE
Optimize the installation experience

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-alb-ingress-controller#726]
Book keeping issue to optimize the installation experience,
so that new users can install ingress controller as easy as  `kubectl apply -f 'pathToOurYamlOnGitHub'`.

- [ ] Omit Ingress controller required params
For the ingress controller to work correctly, three variable are required:
  - [ ] ClusterName(can be introspected from kubernetes.io/cluster/cluster-name:owned tag)
  - [x] VPC_ID(can be introspected from ec2Metadata)
  - [x] AWS REGION(can be introspected from ec2Metadata)
These variable can still be manually specified for advanced use case like `ec2Metadata unavailable` or `running ingress controller on EKS control plane`.
- [x]  Migrate the helm into helm charts repo.(omit the quay.io registry plugin)
- [ ] Create an managed AWS policy to capture the needed IAM permission.

**Comment by AndresPineros** [comment]
Please: omit the quay.io registry plugin. Helm is a tool that usually requires creating wrappers because it lacks some functionalities, this makes it hard to work with those wrappers. Examples of wrappers are "helmfile" and "helmsman". Those don't support something as specific as the Helm Registry Plugin.
