### ISSUE TITLE
ALB Listeners lost on every deployment

### ISSUE THREAD

**Issue by DeNReLoaDeD** [kubernetes-sigs/aws-alb-ingress-controller#762]
Hi,

I have setup ingress-controller on AWS EKS, and everything is working fine, but i have a problem with listeners in the application load balancer. If I manually configure in AWS console a new listener to create a custom rule, everytime I make an apply of deployment.yml I'm loosing this configuration.

There is something I'm missing here? I think this shouldn't be happening, but maybe it's something wrong in my configuration...

Thanks!

**Comment by M00nF1sh** [comment]
Hi，it's due to the controller `fully owns the ALB` and drive it's status to match ingress spec.
Suppose the you created the ingress with 2 listener port via annotations, but then deleted it from ingress, the controller needs to delete that listener too. (We don't have any mechanism to distinguish listeners created by you or by controller).

Currently the controller will only work when there are k8s changes(include ingress/service/endpoints), and will do a force sync for all ingresses every 60minutes(configurable)。

**Comment by DeNReLoaDeD** [comment]
Thank you for your response. 

Tried to add tls on ingress.yml and pointing to our domain, to listen in ports 80 and 443, but still creating only listener on port 80. My ingress file:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service
  namespace: my-ns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
  labels:
    app: service
spec:
  tls:
  - hosts:
    - domain.com
    secretName: my-secret
  rules:
  - host: domain.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: service
          servicePort: 80`

After apply this file:

`NAME                  HOSTS                            ADDRESS                                                                 PORTS     AGE
service   domain.com   XXXXXXXXXXXXX.elb.amazonaws.com   80, 443   22h
`
And listerner in aws console:

![captura de pantalla 2018-12-05 a las 10 13 38](https://user-images.githubusercontent.com/15126439/49502952-85d5a280-f876-11e8-8755-e0874822c350.png)

I don't really know what i'm doing wrong.. any help appreciated.

Thanks, regards!
