### ISSUE TITLE
How to use external dns with an intermediate host?

### ISSUE THREAD

**Issue by backjo** [kubernetes-sigs/aws-alb-ingress-controller#776]
Hi!

In 1.0-beta.7, we had the following setup with DNS and our ALB, with the ALB having the ignore-host-header annotation. 

us-west-2.production.foo.com -> external DNS to ALB
production.foo.com -> CNAME 

When we entered "production.foo.com", it would route correctly to the ALB being maintained by the ingress controller.

From what I can tell, 1.0.0 enforces hostname checks and removes the ignore-host-header annotation, which would break this setup, since we are using a higher level CNAME. Is this correct? And if so, is there any workaround?

**Comment by M00nF1sh** [comment]
Hi, this is apparently an use case missing when we remove the 'ignore-host-header' annotation.
However, i still think that annotation should be removed due to it's violating ingress's spec(especially when dealing with multi host ingresses).
Instead, support for using another DNS name than specified in ingress resource should be supported in external-DNS project instead of alb ingress controller.

Just take a look at  external-dns's code, i think we can achieve the above effect via --fqdn-template setting. I'll test it and get back to you after kubecon 😄

**Comment by backjo** [comment]
@M00nF1sh sounds good - I'll try the same on my side and report back as well - though also busy with Kubecon this week :)

**Comment by backjo** [comment]
So it looks like external-dns actuallly supports the hostname annotation on ingress objects now, so it was pretty easy to use that to solve this use case!

https://github.com/kubernetes-incubator/external-dns/pull/545
