### ISSUE TITLE
Improve error message for auto-discover subnets

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-alb-ingress-controller#777]
Currently the error message for auto-discover subnets always ask users to add `kubernetes.io/role/internal-elb` to their subnets. 

The correct behavior should be ask for `kubernetes.io/role/elb` for internet-facing ingress, and ask for `kubernetes.io/role/internal-elb` for internal ingress.

**Comment by Benjamin-Dobell** [comment]
Hmm, is the controller definitely looking for the presence of `kubernetes.io/role/elb`, and not simply `kubernetes.io/role/internal-elb`?

Because I'm receiving the aforementioned error i.e.

> E1213 18:43:46.392419       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/\u003ccluster name\u003e tag with a value of shared or owned and the kubernetes.io/role/internal-elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were []"  "Controller"="alb-ingress-controller" "Request"={"Namespace":"default","Name":"shared-ingress"}

When I have subnets that are tagged with `elb` rather than `internal-elb` and subnet autodiscovery is not finding them:

```bash
$ aws ec2 describe-subnets --filters "Name=tag:kubernetes.io/cluster/staging.kops.snaploader.com,Values=owned" "Name=tag:kubernetes.io/role/elb,Values=1" | jq '.Subnets | map(.SubnetId)'
[
  "subnet-06c1fd244b64ad97d",
  "subnet-00519b05d8e86df67",
  "subnet-0c8542ed4d3f808c3"
]
```

The Ingress controller containers args includes `- --cluster-name=staging.kops.snaploader.com`.

Are there additional requirements as well?

**Comment by Benjamin-Dobell** [comment]
It seems the Ingress needs to be explicitly annotated as internet facing:

```
alb.ingress.kubernetes.io/scheme: internet-facing
```

where as I'd assumed that was the default.

So seems as this issue is regarding updating the message, it'd be good to indicate clearly whether the Ingress being provisioned is internal or Internet facing. It'd also be nice to see the cluster name correctly substituted into the error message.

**Comment by M00nF1sh** [comment]
> It seems the Ingress needs to be explicitly annotated as internet facing:
> 
> ```
> alb.ingress.kubernetes.io/scheme: internet-facing
> ```
> where as I'd assumed that was the default.
> 
> So seems as this issue is regarding updating the message, it'd be good to indicate clearly whether the Ingress being provisioned is internal or Internet facing. It'd also be nice to see the cluster name correctly substituted into the error message.

Hi, you are correct, it will be nice to clusterName substituted in.
We are looking for  'kubernetes.io/role/elb' for internet-facing ingresses 
and 'kubernetes.io/role/internal-elb' for internal-facing ingresses

The default type is internal instead of internet-facing is for security reasons. I think it will be nice to have a controller flag to control this behavior

**Comment by M00nF1sh** [comment]
Fixed by https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/825
