### ISSUE TITLE
Restrict ALB to be internal scheme only

### ISSUE THREAD

**Issue by mikehalof** [kubernetes-sigs/aws-alb-ingress-controller#807]
Hi,
I do have a requirement from the central IT security team to be able to create ALB only with internal scheme. I'm using EKS and they don't want the ability to create internet-facing ALB
--
alb.ingress.kubernetes.io/scheme: internal
--
I would like something similar to the ingress class (https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#limiting-ingress-class) 

Is that possible?

Thanks,
Mike

**Comment by backjo** [comment]
You can use the scheme annotation to accomplish this -> https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#scheme

```
alb.ingress.kubernetes.io/scheme: internal
```

**Comment by M00nF1sh** [comment]
Hi, you can use an configmap  [alb-ingress-controller-internet-facing-ingresses](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#limiting-external-namespaces) to achieve it in versions from 1.0-beta.6 to v1.0.1. The users will still be create the ingress object, but it will fail reconcile is it's not scheme: internal

This feature is subject to change in future versions, some potential changes are below:
1. Use admission controller to prevent the creation of ingress object instead of fail reconcile.
1. Use a central configMap for all controller-level settings instead of separate ones like "alb-ingress-controller-internet-facing-ingresse".
1. Limiting the ability to create internet-facing ingress based on serviceAccount instead of namespace(or maybe support both case) via admission controller.
