### ISSUE TITLE
Double forward slash after the base part of the URL

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#820]
Hi, I use ALB with ingress and have been having the problem with double forward slash in the url after the host part. For example, https://my.domain.com//api/method. The same cluster deployed on my local laptop using nginx with NodePort does not have this issue at all. Any advice and insight is appreciated.

**Comment by M00nF1sh** [comment]
Hi, what's your ingress spec looks like?
The kubernetes doesn't specify  interpret rules for the path in ingress spec, so different provider uses it's native support to interpret the path rule, which caused different behavior.

How ALB interpret path rule is specified in https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions

**Comment by M00nF1sh** [comment]
@khteh 
I just verified that
1. If you use `//application` as path, then `myapp.mydomain.io//application` will work.
1. If you use `/application/*` as path, then `myapp.mydomain.io/application//api` will work 
😄 Hope above solves your problem

**Comment by khteh** [comment]
@M00nF1sh, //application/* works in my case. Not the others. Any idea if this is the standard / expected behaviour of the ingress? Is it going to change in the future? Thanks.

**Comment by M00nF1sh** [comment]
@khteh 
Hi, the current ingress spec specified path as below in [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#httpingresspath-v1beta1-extensions):
```
Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional "path" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.
```
However, every Ingress Controller(GCE/Nginx/ALB) used it's own native interpretion for path instead of posix regex.

So, under the context the ALB ingress controller, the behavior will not change, and the interpretion for path will be according to https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions 

😄

**Comment by khteh** [comment]
Thanks @M00nF1sh
