### ISSUE TITLE
alb.ingress.kubernetes.io/target-type having instance as "default" option.

### ISSUE THREAD

**Issue by rajarajanpsj** [kubernetes-sigs/aws-alb-ingress-controller#839]
As per the documentation, the default values for alb.ingress.kubernetes.io/target-type is instance. Is there any specific reason why it is not IP. We are using EKS and would it make sense to switch alb.ingress.kubernetes.io/target-type to ip so that load balancing happens directly across the underlying pods? Are there any caveats that we should be aware of?

https://github.com/kubernetes-sigs/aws-alb-ingress-
controller/blob/master/docs/guide/ingress/annotation.md#target-type

**Comment by M00nF1sh** [comment]
@rajarajanpsj 
The default mode is instance instead of ip because it's can be used with any k8s cni. 
You can override the default mode for your cluster by add  `--target-type=ip` to args section of controller yaml.

The downside of mode: ip is that it's hard to achieve zero-downtime-deployment as of now, if your pods number is relatively small. details can be viewed here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/814

**Comment by rajarajanpsj** [comment]
@M00nF1sh  --target-type=ip this is perfect. Thanks!!
