### ISSUE TITLE
isolate path failures

### ISSUE THREAD

**Issue by itaysk** [kubernetes-sigs/aws-alb-ingress-controller#844]
I had a single ingress with multiple paths where one of the paths was misconfigured (service was ClusterIP). This one path sabotaged the creation of the entire ALB (couldn't add targets to targetgroup). Ideally, I'd expect the rest of the paths to provision correctly, and just this misconfigured path to fail.

**Comment by M00nF1sh** [comment]
@itaysk 
Hi, it's hard to isolate paths since the order also matters. suppose ingress rule below:
```
/path/critical: serviceA
/path/*: serviceB
```
If serviceA is unavailable, the behavior changes. (i.e. /path/critical goes to serviceB instead of serviceA).

Is this isolate path failure a real problem? Since you can always get error message on the controller and ingress if anything wrong.
BTW, you can add an "-v=1" flag to the controller yaml, so that whenever you fixed the problem, it will output a "Successfully Reconciled" message.

**Comment by M00nF1sh** [comment]
@mazamats 
Hi, the root cause of your problem should be others. Since even your pods have no health endpoints, the ALB will be fine, as long as your service Object exists.

The "failed to reconcile target groups due to failure to load serviceAnnotation due to no object matching key ***" in local store" error typically happens when we get the notification about ingress object before the service object(when you create them at the same time), and the retry mechanism handles it automatically.

Would you help add an "-v=1" flag to the controller yaml, with this flag it will output a "Successfully Reconciled" message if everything went nice. (otherwise, you may be confused about the outdated error message while everything is already fixed).

**Comment by mazamats** [comment]
@M00nF1sh The retry mechanism is not enough, the issue is that the other paths are not having their target groups updated while the other service is still waiting for pods to be ready.

**Comment by M00nF1sh** [comment]
@mazamats 
But what the root cause that make path2 don't work? the minimal requirement is you have the service object(path2's backend) in kubernetes(pods been not ready is fine and will work)

**Comment by mazamats** [comment]
Like @itaysk stated, the service could be misconfigured causing the same issue. Missing backends should't be breaking the update of the entire ALB.

**Comment by M00nF1sh** [comment]
@mazamats 
Will make these missing backend(or misconfigured backend) to be a default 404 page satisfies your use case? 
We cannot simply ignore misconfigured path since path order matter., e.g. ```
/path/critical: serviceA
/path/*: serviceB
```

**Comment by mazamats** [comment]
@M00nF1sh Can it just be routed to an empty target group? 404 works as well, but I think it makes sense to create the target group anyway.

**Comment by M00nF1sh** [comment]
@mazamats 
empty backend makes sense too. I'll include this in my ingress group support PR.

**Comment by JacobHenner** [comment]
Did this make it into https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1166?

/reopen
/remove-lifecycle rotten

**Comment by M00nF1sh** [comment]
@JacobHenner 
As for rule conflicts, its partially resolved by V2.  A conflict rule will prevent the whole group to reconcile. 
However, The handling of target registration to target groups(and reconcile) is handled by another process called [endpointBinding](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v2/pkg/apis/ingress/v1alpha1/endpointbinding_types.go). So existing target groups will still be updated on target changes(node/pod), even if rules cannot be updated (rules won't be modified too if there are rule conflicts). The only problem is the EndpointBinding currently is stored as in memory structures, so if the controller is died for some reason, it's gone(and conflicting rules will prevent new controller to reconstruct them in memory). 

To solve it, one solution is store the endpoint binding as in-cluster Custom Resource, but it will require user to install such CRD when installing our controller. (however, it also offers benefits like only use that feature to update target groups without using ALB,  some customers can run their whole stack in EC2 while using endpointBinding to update targets for one of their targetGroup).

BTW, the best place to avoid conflicting rules is turn the controller itself into a validation/mutation webhook, which checks the rules and reject changes if there are conflicts 🤣
