### ISSUE TITLE
Support explicit "all" availability zone for IP targets 

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/aws-alb-ingress-controller#858]
For IP targets in a TargetGroup, each target can specify whether it should receive traffic from the ALB nodes in its own AZ or from ALB nodes in all AZs. See the [AvailabilityZone field here](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetDescription.html).

I would like to specify a value of `all` for one of my ingress' services. The specific struct that needs modifying is located here:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/63e5be04f16a562cd839cf2d4520486de99ffe9b/internal/ingress/backend/endpoint.go#L104-L107

I'm just not sure how you would recommend exposing this to the user. A new `alb.ingress.kubernetes.io/availability-zone` annotation on the ingress and service? I could see how it could be easily confused with the `alb.ingress.kubernetes.io/subnets` annotation, so we should document it carefully.

I can open a PR to support this if you can provide guidance on the best way to make this setting configurable.

**Comment by M00nF1sh** [comment]
@rifelpet 
That document is kind of misleading..
In fact, these IPs allocated via ENI must be registered with its AZ(or left empty) instead of 'all'(The AWS API actually enforced it if you try).
And cross-zone loadbalancing is always enabled for ALB. So your service are already receive traffic from alb nodes in all zone.

The "all" target will be needed when supporting the "ip" mode for kubenet. Where these IPs are virtual ip allocated to nodes via route table. To fully support it, we should also figure out the ENI of specific virtual IP by looking up route tables, and attach securityGroups. See #783 for more details.
Will be happy if you can contribute on this, but there should be some refactor work to make the code easier to maintain. (Mainly, the process of find ENI by route table should only happen once instead of both at determine target AvailabilityZone and attach securityGroup).

**Comment by rifelpet** [comment]
@M00nF1sh Thanks for the insight. In my case, I'm actually needing to run the ALB in a different VPC than the cluster, so even with `amazon-vpc-cni-k8s` providing pod IPs within the cluster's VPC, from the ALB's perspective they are outside its VPC CIDR range and would require `AvailabilityZone=all` to work. I realize this is quite an unusual case but if supporting this is required for kubenet, then supporting my scenario natively sounds quite promising. I'm not as concerned about managed security groups, so it sounds like even a partial solution for kubenet would handle my situation well.

I may be able to contribute some of the work towards this. How do you think the aws-alb-ingress-controller should detect if it needs to use `all` for its IP targets? An specific annotation, or possibly automatically comparing the endpoint IPs against the VPC CIDRs?

**Comment by M00nF1sh** [comment]
@rifelpet 
I don't think it's possible for now..since the targetGroup is auto-created using the cluster's VPC. 
If you register targets within this cluster VPC into that targetGroup, the AWS API server actually enforce you to use it's own AZ instead of all.

An alternative for your solution is have an targetGroup CRD like
```
spec:
     arn: xxxx(optional, if not specified,  will auto-create one)
     backend:
         serviceName: string
         servicePort: intstr
status:
    arn:
```
Then the controller can populate targets into that targetGroup, and use the targetGroup VPCID to detect whether to register as ALL. (Mainly we need to support use existing targetGroup outside of VPC).

**Comment by rifelpet** [comment]
I'm able to specify `--aws-vpc-id` argument and the `alb.ingress.kubernetes.io/subnets` annotation on the ingress using subnets from my ALB VPC, and it seems the only issue I'm running into with this setup is the `ALL` parameter.  It sounds like the targetGroup CRD would definitely accomplish what I'm looking for though, so I'm looking forward to that and am willing to contribute towards the implementation and provide feedback.

**Comment by M00nF1sh** [comment]
There was code for doing this in the past https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/1.0-beta.7/internal/aws/albelbv2/elbv2.go#L238.
Would you help check whether it's easy to included the logic to current master? I'm happy to merge it as a temp solution.

**Comment by rifelpet** [comment]
That looks exactly like what I'm looking for, thanks! I'll see if its feasible to include in master and look into opening a PR sometime next week.
