### ISSUE TITLE
How to make AWS credential safe?

### ISSUE THREAD

**Issue by johnzheng1975** [kubernetes-sigs/aws-alb-ingress-controller#859]
I tried aws-alb-ingress-controller, per your [walkthough](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/).

I am concerning how to make my AWS credential safe.
There are two way to get aws right as you introduced (Please correct me if I am wrong)
1  Put AWS_SECRET_ACCESS_KEY in alb-ingress-controller pod directly  (Easy to disclosure)
2  Use [Kube2iam](https://github.com/jtblin/kube2iam#kube2iam)  (A not well known open source whose latest version is **0.10.7-rc3**)
I think both of them are not suitable for production environment, how do you think?

Or Is it possible work around with this way:  After ALB created, I deleted this alb-ingress-controller deployment.  Thus the AWS credential will not be disclosure.
However, can ALB still works fine? Especially when k8s nodes be created/ destroyed automatically during node auto-scaling, will ALB still works if alb-ingress-controller deployment not exists?

Thanks in advance for your answer.

**Comment by M00nF1sh** [comment]
Hi, 
If you delete the alb-ingress-controller deployment, it will not work(since k8s will purge the pods).

A simple solution is:
1. create an IAM policy that contains the permissions needed by alb-ingress-controller.
1. attach the IAM policy to the role for worker nodes.

Another solution is the Kube2iam you mentioned, we'll have [official alternatives](https://github.com/aws/containers-roadmap/issues/23)  available soon.

**Comment by johnzheng1975** [comment]
Seems you did not answer my question.

For simple solution upper, it is similar with your official [workthough](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/#kube2iam-setup)
There is step 3, 4 besides 1, 2, right?

**Comment by johnzheng1975** [comment]
For your simple solution, there should two more steps, right?  (refer to [walkthough](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/) ).
3 create the role, called k8s-alb-controller, attach the above policy and add a Trust Relationship 
4 update the alb-ingress-controller.yaml, Add the annotations in the template's metadata point
So your simple solution is still kube2iam solution, right?

Another thing is, I deleted alb-ingress-controller deployment(pods) after alb is created.
This alb still works so far after 3 hours. 
Any comments?

**Comment by M00nF1sh** [comment]
Hi,
1. There isn't the two more steps you mentioned. Which k8s are you using?(i'm suppose it's kops). Kops already create a role called `nodes.$yourClusterName`,and been attached to your worker nodes. You just need to attach the policy(created for our controller) to that role. 
The way it works is, that role `nodes.$yourClusterName` is your worker node's instance role(which all aws calls make from our worker node will use). So our controller runnings as pod on worker node will use that role to make API calls. 

2. If you deleted the controller, the alb will work(since the controller is already gone, thus it's cannot delete the alb for you). The consequence is, if pods ever get reschedules/restarted, the ALB won't be reconfigured(e.g. add pod's new IP as backend).

**Comment by johnzheng1975** [comment]
Got it, thanks.
