### ISSUE TITLE
Target group selection

### ISSUE THREAD

**Issue by bilby91** [kubernetes-sigs/aws-alb-ingress-controller#913]
Hello,

Today I've been doing some troubleshooting on our ALB setup and realized that all of our instances are getting added to the target group independently on which ones are running the alb controller pod.

Is this the expected behaviour ? The instance that don't have any alb controller pod running are marked as unhealthy really quickly so there is a very small amount of time that a request could potentially be routed to them. 

Want to make sure we don't have something wrong with our setup.

Thanks before hand!

**Comment by M00nF1sh** [comment]
Hi,  This is the expected behavior.
But are you using `external-traffic=Local` in your service? With  `external-traffic=Local`, nodes will only route traffic to pod on it's own machine(the health check will ensure traffic not send to these nodes).
With the default mode `external-traffic=Cluster`, nodes will route traffic to pods(maybe on another node), so that all nodes can be used as target, no matter there are pods on it or not.

**Comment by M00nF1sh** [comment]
BTW, you may be intested in [`alb.ingress.kubernetes.io/target-type: ip`](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#target-type) if you are using EKS's CNI. Which will directly register pods ip as targets.

**Comment by bilby91** [comment]
@M00nF1sh target-ip is exactly what I was looking for. This actually solved some issues that we were having with kube-proxy not handling the health check correctly.

Thanks!!
