### ISSUE TITLE
Cognito rule is not created

### ISSUE THREAD

**Issue by riponbanik** [kubernetes-sigs/aws-alb-ingress-controller#944]
I have setup congito authentication following the link below, the http/https rule is created but not coginto rule. I have given cognito permission to the nodes.

https://kubernetes-sigs.github.io/aws-alb-ingress-controller/examples/cognito-ingress-template.yaml

The log from the controller is here -

https://gist.github.com/riponbanik/51a714167f536783fc7a2cc425eb771b

**Comment by thomeudt** [comment]
I ran into the same issue today, alb otherwise deploys correctly (and works) but the cognito rule is not created.

**Comment by thomeudt** [comment]
Turns out the issue is that I followed a tutorial to set up the alb-ingress-controller in first place and added cognito support later. That tutorial referenced a manifest file for version 1.0.0 of the controller image, which indeed did not include cognito support. 

Updating alb-ingress-controller.yaml and switching from

          # Repository location of the ALB Ingress Controller.
          image: 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-alb-ingress-controller:v1.0.0
 
to

          # Repository location of the ALB Ingress Controller.
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.2

solved the problem for me.

**Comment by riponbanik** [comment]
@thomeudt Thanks that works. Still one more issue, we need to have default forward after authentication before 404. Have you figured that out as well?
